node {
  stage('do something with git') {  
    sshagent (credentials: ['git-key']) {
      // get the last commit id from a repository you own
      // sh 'git ls-remote -h --refs git@github.com:FJGL/jenkins-course.git master |awk "{print $1}"'
      sh 'git ls-remote -h --refs git@github.com:FJGL/jenkins-course.git master '
    }
  }
}
